# Generated by scripts/champion/prepare_champion.py; do not edit.
from fair_offline_assessor.models import ResourceRef

DEFINITIONS: tuple[ResourceRef, ...] = (
    ResourceRef(
        id="champion:tests",
        version="0.5.12",
        kind="reference",
        format="json",
        digest="f71412bcc78488a05e09ffaf52f197d6efb62b98bd35dd65a179e977bf76cd90",
    ),
    ResourceRef(
        id="champion:references",
        version="0.5.12",
        kind="reference",
        format="json",
        digest="d01d09c2dd81b198fd8e2ea807d34c146be778751ecef20cc9c04fdc1f102e6e",
    ),
    ResourceRef(
        id="champion:offline-policy",
        version="0.5.12",
        kind="reference",
        format="json",
        digest="21daa161eec452f3cbfc10f9c02ef2645209fcc85a15c449449a9aa252828a29",
    ),
    ResourceRef(
        id="champion:upstream",
        version="0.5.12",
        kind="reference",
        format="json",
        digest="9e91e5c6670d9e675323ab868504b00d42ce653fb5e841c0bcb14daf53163f43",
    ),
)
