# SPDX-FileCopyrightText: 2020 PANGAEA (https://www.pangaea.de/)
#
# SPDX-License-Identifier: MIT

# coding: utf-8

from datetime import date, datetime  # noqa: F401

from fair_offline_assessor._vendor.fuji.v3_5_1 import util
from fair_offline_assessor._vendor.fuji.v3_5_1.models.base_model_ import Model


class Debug(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):
        """Debug - a model defined in Swagger"""
        self.swagger_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "Debug":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Debug of this Debug.  # noqa: E501
        :rtype: Debug
        """
        return util.deserialize_model(dikt, cls)
